# Generated by Django 5.0.2 on 2024-02-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
